name: Process Git Diff on Push

on:
  push:
    branches:
      - main  # Change to the branch you want to track

jobs:
  get-diff-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we get the previous commit for diff comparison

      - name: Get Diff from Last Commit
        run: |
          git diff HEAD^ HEAD > push-diff.txt

      - name: Display Diff
        run: |
          echo "Showing first 50 lines of the diff:"
          head -n 50 push-diff.txt

      - name: Run Diff Processing
