name: Process Git Diff on Push

on:
  push:
    branches:
      - main

jobs:
  get-diff-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Diff from Last Commit
        run: |
          git diff HEAD^ HEAD > push-diff.txt

      - name: Display Diff
        run: |
          echo "Showing first 50 lines of the diff:"
          head -n 50 push-diff.txt

      - name: Install PydanticAI
        run: |
          pip install pydantic-ai


      - name: Run Diff Processing Script
        run: python process_diff.py push-diff.txt
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
